# Generated by Django 4.0.4 on 2022-09-05 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='hidden',
        ),
        migrations.AddField(
            model_name='idea',
            name='bonus',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='idea',
            name='bonus_answer',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=2202, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birtdhay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
