# Generated by Django 4.0.4 on 2022-09-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_remove_idea_hidden_idea_bonus_idea_bonus_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='tags',
            new_name='tag',
        ),
    ]
