# Generated by Django 4.0.4 on 2022-09-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_rename_tags_idea_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='bonus',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='bonus_answer',
            field=models.IntegerField(blank=True),
        ),
    ]
