# Generated by Django 4.0.4 on 2022-09-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_alter_idea_bonus_alter_idea_bonus_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('question', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='idea',
            name='bonus',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='idea',
            name='bonus_answer',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
