# Generated by Django 4.0.4 on 2022-09-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_bonus_alter_idea_bonus_alter_idea_bonus_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='bonus_answer',
        ),
    ]
